# This rule is not used by the project transition-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to transition.dcnlab.ssu.ac.kr resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: transition-operator
    app.kubernetes.io/managed-by: kustomize
  name: nodehealth-viewer-role
rules:
- apiGroups:
  - transition.dcnlab.ssu.ac.kr
  resources:
  - nodehealths
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - transition.dcnlab.ssu.ac.kr
  resources:
  - nodehealths/status
  verbs:
  - get
