---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - transition.dcnlab.ssu.ac.kr
  resources:
  - checkpoints
  - clusterpolicies
  - packagepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - transition.dcnlab.ssu.ac.kr
  resources:
  - checkpoints/finalizers
  - clusterpolicies/finalizers
  - packagepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - transition.dcnlab.ssu.ac.kr
  resources:
  - checkpoints/status
  - clusterpolicies/status
  - packagepolicies/status
  verbs:
  - get
  - patch
  - update
