# propagationpolicy-update.yaml
apiVersion: transition.dcnlab.ssu.ac.kr/v1
kind: ClusterPolicy
metadata:
  name: clusterpolicy-sample
spec:
  clusterSelector:
    name: edge
    repo: http://192.168.28.187:31969/nephio/edge.git
    repoType: git
  selectMode: Specific # Specific, All
  transitionMode: Manual # Automatic, Manual
  packageSelectors:
    - name: nginx
      packagePath: nginx
      packageType: Stateless # Stateless, Stateful
      selected: true
  packageRetentionPolicy:
    retainOnSource: false
    deleteAfterTransition: true
  targetClusterPolicy:
    preferClusters:
      - name: regional
        # repo: http://192.168.28.187:31969/nephio/core.git ## i think this might not be needed because we dont push the transitionresource to this repo
        repoType: git
        weight: 100
    # avoidClusters:
    #   - name: dev-local
    #     repo: http://192.168.28.187:31969/nephio/core.git
    #     repoType: git
