# propagationpolicy-update.yaml
apiVersion: transition.dcnlab.ssu.ac.kr/v1
kind: ClusterPolicy
metadata:
  name: clusterpolicy-sample
spec:
  clusterSelector:
    name: cluster1-aws
    repo: http://13.214.181.179:30343/nephio/cluster1-aws.git # repo where the cluster workloads is defined
    repoType: git
  selectMode: Specific # Specific, All ---> REMOVE
  packageSelectors:
    - name: wordpress # Package Name
      packagePath: wordpress-app # where the package is in the repo
      packageType: Stateful # Stateless, Stateful
      liveStatePackage: true
      backupInformation:
        - name: cluster1vt-backup # Backup Name
          backupType: Manual # Manual, Schedule
        - name: core-backup-every-1-min # Schedule Name
          backupType: Schedule # Manual, Schedule
          schedulePeriod: "*/1 * * * *" # cron format
  targetClusterPolicy:
    preferClusters:
      - name: cluster2-azure
        repoType: git
        weight: 100
