# propagationpolicy-update.yaml
apiVersion: transition.dcnlab.ssu.ac.kr/v1
kind: ClusterPolicy
metadata:
  name: clusterpolicy-sample
spec:
  clusterSelector:
    name: cluster1
    repo: http://192.168.28.137:30524/nephio/cluster1vt.git
    repoType: git
  selectMode: Specific # Specific, All
  transitionMode: Manual # Automatic, Manual
  packageSelectors:
    - name: wordpress
      packagePath: wordpress
      packageType: Stateful # Stateless, Stateful
      selected: true
      backupInfomation:
        - name: cluster1-backup # Backup Name
          backupType: Manual # Manual, Schedule
        - name: cluster1-backup-every-5-min # Schedule Name
          backupType: Schedule # Manual, Schedule
  packageRetentionPolicy:
    retainOnSource: false
    deleteAfterTransition: true
  targetClusterPolicy:
    preferClusters:
      - name: cluster2vt
        # repo: http://192.168.28.187:31969/nephio/core.git ## i think this might not be needed because we dont push the transitionresource to this repo
        repoType: git
        weight: 100
    # avoidClusters:
    #   - name: dev-local
    #     repo: http://192.168.28.187:31969/nephio/core.git
    #     repoType: git
