# propagationpolicy-update.yaml
apiVersion: transition.dcnlab.ssu.ac.kr/v1
kind: ClusterPolicy
metadata:
  name: clusterpolicy-sample
spec:
  clusterSelector:
    name: cluster1-capo
    repo: http://192.168.28.111:31650/nephio/cluster1-capo.git # repo where the cluster workloads is defined
    repoType: git
  selectMode: Specific # Specific, All ---> REMOVE
  packageSelectors:
    - name: video # Package Name
      packagePath: video # where the package is in the repo
      packageType: Stateful # Stateless, Stateful
      liveStatePackage: true
      backupInformation:
        # - name: my-test-backup # Backup Name
        #   backupType: Manual # Manual, Schedule
        - name: my-test-backup # Schedule Name
          backupType: Schedule # Manual, Schedule
          schedulePeriod: "*/3 * * * *" # cron format
  targetClusterPolicy:
    preferClusters:
      - name: migrationdev
        repoType: git
        weight: 100
