# propagationpolicy-update.yaml
apiVersion: transition.dcnlab.ssu.ac.kr/v1
kind: ClusterPolicy
metadata:
  name: clusterpolicy-sample
spec:
  clusterSelector:
    name: kt-cluster1
    repo: http://13.214.38.114:30178/nephio/kt-cluster1.git # repo where the cluster workloads is defined
    repoType: git
  selectMode: Specific # Specific, All
  transitionMode: Manual # Automatic, Manual
  packageSelectors:
    - name: wordpress-app # Package Name
      packagePath: wordpress-app # where the package is in the repo
      packageType: Stateful # Stateless, Stateful
      selected: true
      backupInformation:
        - name: cluster1vt-backup # Backup Name
          backupType: Manual # Manual, Schedule
        - name: core-backup-every-5-min # Schedule Name
          backupType: Schedule # Manual, Schedule
  packageRetentionPolicy:
    retainOnSource: false
    deleteAfterTransition: true
  targetClusterPolicy:
    preferClusters:
      - name: aws-cluster1-standby
        # repo: http://192.168.28.187:31969/nephio/core.git ## i think this might not be needed because we dont push the transitionresource to this repo
        repoType: git
        weight: 100
    # avoidClusters:
    #   - name: dev-local
    #     repo: http://192.168.28.187:31969/nephio/core.git
    #     repoType: git
