apiVersion: transition.dcnlab.ssu.ac.kr/v1
kind: Checkpoint
metadata:
  labels:
    app.kubernetes.io/name: transition-operator
    app.kubernetes.io/managed-by: kustomize
  name: checkpoint-sample
spec:
  clusterRef:
    name: cluster1-capo
  podRef:
    name: test-pod
    namespace: default
  registry:
    repository: vitu1
    secretRef:
      name: reg-credentials
      namespace: default
    url: docker.io
  resourceRef:
    apiVersion: apps/v1
    kind: Pod
    name: my-app
    namespace: default
  schedule: 0/1 * * * *