apiVersion: transition.dcnlab.ssu.ac.kr/v1
kind: Checkpoint
metadata:
  labels:
    app.kubernetes.io/name: transition-operator
    app.kubernetes.io/managed-by: kustomize
  name: checkpoint-sample

spec:
  schedule: 0/1 * * * *
  targetClusterRef:
    name: migrationdev
  clusterRef:
    name: cluster1-capo
    repository: http://13.214.181.179:30343/nephio/cluster1-aws.git
  containers:
  - image: registry.mydomain.com/lehuannhatrang/checkpoints:app-container
    name: app-container
  - image: registry.mydomain.com/lehuannhatrang/checkpoints:sidecar-container
    name: sidecar-container
  podRef:
    name: video
    namespace: default
  registry:
    repository: vitu1
    secretRef:
      name: reg-credentials
      namespace: default
    url: docker.io
  # resourceRef:
  #   apiVersion: apps/v1
  #   kind: Pod
  #   name: my-app
  #   namespace: default

